import { query, withTransaction } from "@/lib/db";
import { ensureTripForDispatch, syncVehicleStatus, syncDriverStatus } from "@/services/status.service";
import { flushOutbox } from "@/services/push.service";
import { resolveRouteForRequest } from "@/services/route-resolver.service";

// Auto-create a dispatch (+ its trip) the moment a full vehicle+driver pair is
// committed to a transportation request — GAP-FIX: previously the assign
// endpoint only recorded vehicle/driver on the request row, so an assigned
// request never appeared on the Dispatch board or the driver's mobile trip list.
//
// Intentionally scoped to a FULL pair (both vehicle_id and driver_id): a dispatch
// row and its trip are meaningless without both halves. Partial assigns stay at
// `Assigned` on the request and simply never raise a dispatch.
//
// Best-effort by design. The caller (the assign endpoint) has already committed
// the assignment; a failure here must never roll that back, so callers wrap this
// in try/catch.

/**
 * Create (or return the existing) dispatch for a fully-assigned request.
 *
 * @param {object}  opts
 * @param {object}  opts.request  the transportation_requests row (must carry
 *                                request_id, pickup_datetime, pickup_location,
 *                                dropoff_location, guest_name, …)
 * @param {number}  opts.vehicleId
 * @param {number}  opts.driverId
 * @param {object}  [opts.session] caller identity (employeeId for created_by)
 * @returns {Promise<object|null>} the dispatch row, or null when not a full pair
 */
export async function createDispatchForRequest({ request, vehicleId, driverId, session }) {
  // Full-pair gate: only commit resources to a dispatch when BOTH halves exist.
  if (!request?.request_id || !vehicleId || !driverId) return null;

  const employeeId = session?.user?.employeeId ?? null;

  return withTransaction(async (tx) => {
    // Idempotency: never raise a second live dispatch for the same request.
    const existing = await tx.query(
      `SELECT * FROM dispatchschedules
        WHERE request_id = $1 AND deleted_at IS NULL
        ORDER BY dispatch_id DESC LIMIT 1`,
      [request.request_id]
    );
    if (existing.rows[0]) return existing.rows[0];

    // Resolve a route for the pickup->dropoff leg. Unknown free-text legs stay
    // ad-hoc (route_id remains null); only canonical location pairs may create
    // a reusable route.
    const resolvedRoute = await resolveRouteForRequest(tx, request);
    const routeId = resolvedRoute?.route_id ?? null;

    // Dispatch row. scheduled_arrival is intentionally left null — transport
    // requests do not carry an arrival time. dispatch_number is generated by the
    // trg_dispatch_number trigger; when that trigger is absent (fresh DBs where
    // this migration hasn't run) we fall back to a timestamp-based number so the
    // NOT NULL constraint can never silently break the insert.
    const notes = [
      request.dropoff_location ? `Dropoff: ${request.dropoff_location}` : null,
      request.guest_name ? `Guest: ${request.guest_name}` : null,
      request.special_requests ? `Request: ${request.special_requests}` : null,
    ].filter(Boolean).join("\n") || null;

    let dispatch;
    try {
      const ins = await tx.query(
        `INSERT INTO dispatchschedules
           (request_id, vehicle_id, driver_id, route_id, scheduled_departure,
            scheduled_arrival, status, notes, created_by, updated_by)
         VALUES ($1, $2, $3, $4, $5, $6, 'Scheduled', $7, $8, $8)
         RETURNING *`,
        [
          request.request_id,
          vehicleId,
          driverId,
          routeId,
          request.pickup_datetime ?? null,
          null, // scheduled_arrival
          notes,
          employeeId,
        ]
      );
      dispatch = ins.rows[0];
    } catch (e) {
      // Missing dispatch_number = the trigger migration hasn't been applied yet.
      if (/dispatch_number/.test(e?.message || "")) {
        const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        let suffix = "";
        for (let i = 0; i < 4; i++) suffix += chars[Math.floor(Math.random() * chars.length)];
        const fallback = `DSP-${suffix}`;
        const ins = await tx.query(
          `INSERT INTO dispatchschedules
             (request_id, vehicle_id, driver_id, route_id, scheduled_departure,
              scheduled_arrival, status, notes, dispatch_number, created_by, updated_by)
           VALUES ($1, $2, $3, $4, $5, $6, 'Scheduled', $7, $8, $9, $9)
           RETURNING *`,
          [
            request.request_id,
            vehicleId,
            driverId,
            routeId,
            request.pickup_datetime ?? null,
            null,
            notes,
            fallback,
            employeeId,
          ]
        );
        dispatch = ins.rows[0];
      } else {
        throw e;
      }
    }

    return dispatch;
  });
}

/**
 * Apply the side-effects that mirror POST /api/dispatch: create the mobile trip
 * row and keep vehicle/driver availability in sync. Fire-and-forget friendly —
 * the caller awaits it but a failure here is worth surfacing in logs, not a 500.
 */
export async function syncDispatchSideEffects(dispatchId) {
  if (!dispatchId) return;
  const jobs = [
    ensureTripForDispatch(dispatchId).catch((e) =>
      console.warn("ensureTripForDispatch failed:", e?.message || e)
    ),
    // The DB trigger enqueued a loud push for the assigned driver; deliver it.
    flushOutbox().catch((e) =>
      console.warn("flushOutbox failed:", e?.message || e)
    ),
  ];
  const { rows } = await query(
    `SELECT vehicle_id, driver_id FROM dispatchschedules WHERE dispatch_id = $1`,
    [dispatchId]
  );
  const row = rows[0];
  if (row?.vehicle_id) {
    jobs.push(syncVehicleStatus(row.vehicle_id).catch((e) =>
      console.warn("syncVehicleStatus failed:", e?.message || e)
    ));
  }
  if (row?.driver_id) {
    jobs.push(syncDriverStatus(row.driver_id).catch((e) =>
      console.warn("syncDriverStatus failed:", e?.message || e)
    ));
  }
  await Promise.all(jobs);
}
