import { readFileSync } from 'node:fs';
import pg from 'pg';
import { describe, expect, it } from 'vitest';
import { loadEnvLocal } from '../../../scripts/load-env.mjs';

describe.skipIf(process.env.FLEETOPS_REVIEW_DB_TEST !== '1')('typed migration PostgreSQL catalog regression', () => {
  it('applies 151 to a pre-typed clone and reruns with a persisted cargo row', async () => {
    if (!process.env.DATABASE_URL) loadEnvLocal();
    const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false }, connectionTimeoutMillis: 5000 });
    const client = await pool.connect();
    try {
      await client.query('BEGIN');
      await client.query('SET LOCAL statement_timeout = 15000');
      for (const table of ['transportation_requests', 'service_types']) {
        await client.query(`CREATE TEMP TABLE "${table}" (LIKE public."${table}" INCLUDING CONSTRAINTS) ON COMMIT DROP`);
      }
      await client.query('SET LOCAL search_path = pg_temp, pg_catalog');
      // These changes affect empty, session-local clones only. No defaults,
      // production sequences, foreign keys, triggers, or business rows are copied.
      await client.query('ALTER TABLE pg_temp.transportation_requests DROP COLUMN load_type CASCADE, DROP COLUMN cargo_weight_kg CASCADE, DROP COLUMN cargo_description CASCADE, DROP COLUMN source_department CASCADE');
      await client.query('ALTER TABLE pg_temp.transportation_requests ALTER COLUMN passenger_count SET NOT NULL, ALTER COLUMN passenger_count SET DEFAULT 1');
      await client.query('ALTER TABLE pg_temp.service_types DROP COLUMN service_code CASCADE, DROP COLUMN default_load_type CASCADE');
      await client.query('ALTER TABLE pg_temp.service_types ALTER COLUMN service_type_id ADD GENERATED BY DEFAULT AS IDENTITY');
      await client.query("INSERT INTO pg_temp.transportation_requests(request_id,source_system,pickup_location,pickup_datetime,priority,fleet_status,is_vip,is_emergency,passenger_count) VALUES(11,'PMS','Isolated migration fixture',NOW(),'Low','Pending',false,false,2)");
      const { rows: [namespace] } = await client.query('SELECT nspname FROM pg_namespace WHERE oid = pg_my_temp_schema()');
      expect(namespace.nspname).toMatch(/^pg_temp_\d+$/);
      // Run the reviewed SQL body unchanged except its namespace and outer
      // transaction wrapper. Live application remains exclusively db:up's job.
      const migration = readFileSync('supabase/migrations/151_load_types_and_services.sql', 'utf8')
        .replace(/^BEGIN;\s*/m, '').replace(/COMMIT;\s*$/, '')
        .replace(/\bpublic\./g, `"${namespace.nspname}".`)
        .replace(/'public'/g, `'${namespace.nspname}'`);
      await client.query(migration);
      const legacy = (await client.query('SELECT load_type, passenger_count FROM pg_temp.transportation_requests WHERE request_id=11')).rows[0];
      expect(legacy).toEqual({ load_type: null, passenger_count: 2 });
      await client.query("INSERT INTO pg_temp.transportation_requests(request_id,source_system,pickup_location,pickup_datetime,priority,fleet_status,is_vip,is_emergency,load_type,passenger_count,cargo_weight_kg,cargo_description) VALUES(12,'POS','Isolated cargo fixture',NOW(),'Low','Pending',false,false,'Cargo',NULL,650,'Review supplies')");
      for (const table of ['_expected_service_default_load_type', '_expected_transport_typed_load']) await client.query(`DROP TABLE pg_temp."${table}"`);
      await client.query(migration);
      expect((await client.query('SELECT load_type, passenger_count, cargo_weight_kg FROM pg_temp.transportation_requests WHERE request_id=12')).rows[0]).toEqual({ load_type: 'Cargo', passenger_count: null, cargo_weight_kg: '650.000' });
      expect((await client.query('SELECT count(*)::int AS count FROM pg_temp.service_types WHERE service_code IS NOT NULL')).rows[0].count).toBe(5);
    } finally {
      try { await client.query('ROLLBACK'); } finally { client.release(); await pool.end(); }
    }
  }, 60000);
});
