-- ============================================
-- RBAC RLS POLICIES — Phase 1 (Routes & Fuel)
-- ============================================
-- Covers tables that had RLS enabled but zero
-- or incomplete policies: routes, fuelstations,
-- fuelconsumption, fuelrequests, fuelallocations,
-- fuelrecords.
-- Based on docs/rbac-model.md §5.
-- ============================================

-- ============================================
-- HELPER: Get current employee's branch_id
-- ============================================
CREATE OR REPLACE FUNCTION get_current_employee_branch()
RETURNS INT AS $$
DECLARE
  user_branch INT;
BEGIN
  SELECT e.branch_id INTO user_branch
  FROM employees e
  WHERE e.user_id = auth.uid()
  LIMIT 1;
  RETURN user_branch;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- HELPER: Get current employee_id
-- ============================================
CREATE OR REPLACE FUNCTION get_current_employee_id()
RETURNS INT AS $$
DECLARE
  emp_id INT;
BEGIN
  SELECT e.employee_id INTO emp_id
  FROM employees e
  WHERE e.user_id = auth.uid()
  LIMIT 1;
  RETURN emp_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- HELPER: Get current driver_id (NULL if N/A)
-- ============================================
CREATE OR REPLACE FUNCTION get_current_driver_id()
RETURNS INT AS $$
DECLARE
  drv_id INT;
BEGIN
  SELECT d.driver_id INTO drv_id
  FROM drivers d
  JOIN employees e ON d.employee_id = e.employee_id
  WHERE e.user_id = auth.uid()
  LIMIT 1;
  RETURN drv_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- ROUTES  (§5.7)
-- ============================================

CREATE POLICY "All authenticated can view routes"
  ON routes FOR SELECT
  USING (deleted_at IS NULL);

CREATE POLICY "Admin fleet dispatcher can insert routes"
  ON routes FOR INSERT
  WITH CHECK (has_role(ARRAY['admin', 'fleet_manager', 'dispatcher', 'system_admin']));

CREATE POLICY "Admin fleet dispatcher can update routes"
  ON routes FOR UPDATE
  USING (has_role(ARRAY['admin', 'fleet_manager', 'dispatcher', 'system_admin']));

CREATE POLICY "Admin can delete routes"
  ON routes FOR DELETE
  USING (has_role(ARRAY['admin', 'system_admin']));

-- ============================================
-- FUEL STATIONS  (§5.14)
-- ============================================

CREATE POLICY "All authenticated can view fuel stations"
  ON fuelstations FOR SELECT
  USING (deleted_at IS NULL);

CREATE POLICY "Admin can manage fuel stations"
  ON fuelstations FOR INSERT
  WITH CHECK (has_role(ARRAY['admin', 'system_admin']));

CREATE POLICY "Admin can update fuel stations"
  ON fuelstations FOR UPDATE
  USING (has_role(ARRAY['admin', 'system_admin']));

CREATE POLICY "Admin can delete fuel stations"
  ON fuelstations FOR DELETE
  USING (has_role(ARRAY['admin', 'system_admin']));

-- ============================================
-- FUEL CONSUMPTION  (§5.14)
-- ============================================

CREATE POLICY "Operational roles can view fuel consumption"
  ON fuelconsumption FOR SELECT
  USING (has_role(ARRAY['admin', 'fleet_manager', 'system_admin', 'dispatcher', 'management']));

-- INSERT/UPDATE/DELETE are system-only (generated by analytics);
-- no role-based policies are created for mutations.

-- ============================================
-- FUEL REQUESTS  (§5.14)
-- ============================================

CREATE POLICY "All authenticated can view fuel requests"
  ON fuelrequests FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Authorized roles can create fuel requests"
  ON fuelrequests FOR INSERT
  WITH CHECK (has_role(ARRAY['driver', 'admin', 'fleet_manager', 'system_admin']));

CREATE POLICY "Admin fleet manager can approve fuel requests"
  ON fuelrequests FOR UPDATE
  USING (has_role(ARRAY['admin', 'fleet_manager', 'system_admin']));

CREATE POLICY "Admin can delete fuel requests"
  ON fuelrequests FOR DELETE
  USING (has_role(ARRAY['admin', 'system_admin']));

-- ============================================
-- FUEL ALLOCATIONS  (§5.14)
-- ============================================

CREATE POLICY "Operational roles can view fuel allocations"
  ON fuelallocations FOR SELECT
  USING (has_role(ARRAY['admin', 'fleet_manager', 'system_admin', 'management']));

CREATE POLICY "Admin fleet manager can manage fuel allocations"
  ON fuelallocations FOR INSERT
  WITH CHECK (has_role(ARRAY['admin', 'fleet_manager', 'system_admin']));

CREATE POLICY "Admin fleet manager can update fuel allocations"
  ON fuelallocations FOR UPDATE
  USING (has_role(ARRAY['admin', 'fleet_manager', 'system_admin']));

CREATE POLICY "Admin fleet manager can delete fuel allocations"
  ON fuelallocations FOR DELETE
  USING (has_role(ARRAY['admin', 'fleet_manager', 'system_admin']));

-- ============================================
-- FUEL RECORDS  (§5.14)
-- ============================================
-- Drop the overly permissive policies from 002
-- and replace with properly scoped ones.
DROP POLICY IF EXISTS "Drivers can insert fuel records" ON fuelrecords;
DROP POLICY IF EXISTS "Admin can view all fuel records" ON fuelrecords;

CREATE POLICY "All authenticated can view fuel records"
  ON fuelrecords FOR SELECT
  USING (deleted_at IS NULL);

CREATE POLICY "Authenticated can insert fuel records"
  ON fuelrecords FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admin fleet manager can update fuel records"
  ON fuelrecords FOR UPDATE
  USING (has_role(ARRAY['admin', 'fleet_manager', 'system_admin']));

CREATE POLICY "Admin can delete fuel records"
  ON fuelrecords FOR DELETE
  USING (has_role(ARRAY['admin', 'system_admin']));