-- ============================================
-- MIGRATION 103: app_errors — centralized unexpected-failure log
--
-- Owns UNEXPECTED application/platform failures (server 500s, web/mobile
-- crashes, DB/runtime failures). Specialized subsystems own their expected
-- operational failures (AI provider/timeout/parse/quota → ailogs, etc.).
--
-- The write gate is proof-of-persistence, not codes or routes: a row is
-- skipped only when the owning subsystem marked the error subsystemOwned
-- AFTER its own log write succeeded (see src/lib/app-errors.js). A known
-- subsystem code WITHOUT the marker is still captured here as fallback,
-- so an error is never lost merely because its code names another subsystem.
--
-- Deliberately NO foreign key to employees: a log write must never fail on
-- referential integrity (e.g. a just-deleted account). No RLS changes either
-- (RLS is inert by design; the read API enforces audit-read permission).
-- Idempotent: safe no-op when the table already exists.
-- ============================================

CREATE TABLE IF NOT EXISTS app_errors (
  error_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL DEFAULT 'server'
    CONSTRAINT app_errors_source_check CHECK (source IN ('server', 'web', 'mobile')),
  route text NULL,
  message text NOT NULL,
  stack text NULL,
  status_code integer NULL,
  employee_id integer NULL,
  fingerprint text NOT NULL,
  user_agent text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_app_errors_created
  ON app_errors (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_errors_fingerprint
  ON app_errors (fingerprint, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_errors_source
  ON app_errors (source, created_at DESC);
